name: 'Chosen Royals '
analytics: {}
github: true
description: Christian Apparel and Accessories
author:
  email: chosenroyals@mail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.5
color:
  lightness: 0.9297484995168048
  brandColors:
    - '#00585F'
    - '#009393'
    - '#FFFCC4'
    - '#F0EDBB'
    - '#FF3800'
  saturation: 0.06688963879525886
  brandStrength: 0.02920557582499589
  rhythmicContrast: 0.6101924710930773
content_rating:
  adult: false
typography_spectrum: 0.5
opengraph: {}
title: Chosen Royals Co.
